
# if __name__ == '__main__':
#     radio = Radio()
#     radio.mast_aws()
#     analyzer = Analyzer()
#     analyzer.atomic_vector_plotter()
#     analyzer.make_specgram()
#     analyzer.planet_hunter()
#     transformer = Transformer()
#     transformer.hypersonic_pliers()
#     transformer.thermo_fusion_chisel()
#     transformer.babel_fish_dispenser()
#     transformer.fast_fourier()
#     builder = Builder()
#     builder.build_cnn()
#     builder.fit_cnn()
#     computer = Computer()
#     computer.get_preds()
#     computer.fnfp()
#     computer.keras_history()
#     computer.fusion_matrix()
#     computer.roc_plots()
#     computer.compute()
